name: End-To-End Tests

on:
  push:
    branches: [ main ]

jobs:
  e2e-tests:

    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.x
          cache: npm

      - name: Install
        run: |
          npm ci
          npm i -g appium

      - name: Start Appium
        continue-on-error: true
        run: |
          which appium
          appium -v
          appium &

      - name: Run End-To-End Test
        uses: reactivecircus/android-emulator-runner@v2
        continue-on-error: true
        with:
          api-level: 29
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          emulator-build: 7425822
          script: npm run e2e:cucumber:android:suite_product

      - name: Upload Logs
        uses: actions/upload-artifact@v3
        with:
          name: Logs
          path: logs
