name: End-To-End Tests

on:
  push:
    branches: [ main ]

jobs:
  e2e-tests:

    runs-on: ubuntu-20.04

    continue-on-error: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.x
          cache: npm

      - name: Get cache key for node_modules
        id: cache-node-modules
        run: echo "::set-ouput name=date::$(date + '%>-%m-%W')"

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ steps.cache-node-modules.outputs.date }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-${{ steps.cache-node-modules.outputs.date }}-
            ${{ runner.os }}-node-modules-

      - name: Install
        run: |
          npm ci
          npm i -g appium

      #- name: Install and start the emulator
      #  run: |
      #    chmod +x ./emulator.sh
      #    ./emulator.sh
      #  shell: bash

      #- name: Start the Appium Server
      #  run: ./node_modules/.bin/appium --log-timestamp --log-no-colors --allow-insecure chromedriver_autodownload > logs/appium.log

      #- name: Poll for Appium Server to Start
      #  run: |
      #    until $(curl --output /dev/null --silent --head --fail http://127.0.0.1:4723/wd/hub/sessions); do
      #      sleep 5
      #    done

      #- name: Run End-To-End Test
      #  run: npm run e2e:cucumber:android:suite_product
      #  uses: reactivecircus/android-emulator-runner@v2
      #  with:
      #    api-level: 29
      #    script: npm run e2e:cucumber:android:suite_product

      - name: Install and start the emulator
        run: |
          echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd --force --name Pixel_3a_API_34_extension_level_7_arm64-v8a --abi google_apis_playstore/x86_64 --package "system-images;android-29;google_apis_playstore/x86_64"
          $ANDROID_HOME/emulator/emulator -avd Pixel_3a_API_34_extension_level_7_arm64-v8a -no-window -no-audio -no-boot-anim &

      - name: Start the Appium Server
        run: |
          chmod +x ./android-wait-for-emulator.sh
          ./android-wait-for-emulator.sh
          adb shell input keyevent 82
        shell: bash

      - name: Start Appium
        run: appium &

      - name: Run End-To-End Test
        run: npm run e2e:cucumber:android:suite_product

      - name: Upload Logs
        uses: actions/upload-artifact@v3
        with:
          name: Logs
          path: logs
