name: End-To-End Tests

on:
  push:
    branches: [ main ]

jobs:
  e2e-tests:

    runs-on: ubuntu-20.04

    continue-on-error: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.x
          cache: npm

      - name: Install
        run: npm ci

      - name: Run End-To-End Test
        #uses: reactivecircus/android-emulator-runner@v2
        #with:
          #api-level: 29
          #script: ./gradlew connectedAndroidTest
        run: |
          chmod +x ./emulator.sh
          ./emulator.sh
          npm run e2e:cucumber:android:suite_product
        shell: bash

      - name: Upload Logs
        uses: actions/upload-artifact@v3
        with:
          name: Logs
          path: logs
